# cloudbuild.yaml
steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: Build Docker Image
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/backendservicenawr', '.']

  - name: 'gcr.io/cloud-builders/docker'
    id: Push Docker Image
    args: ['push', 'gcr.io/$PROJECT_ID/backendservicenawr']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: Deploy to Cloud Run
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'backendservicenawr',
        '--image', 'gcr.io/$PROJECT_ID/backendservicenawr',
        '--region', 'us-central1',
        '--platform', 'managed',
        '--allow-unauthenticated'
      ]

images:
  - 'gcr.io/$PROJECT_ID/backendservicenawr'

options:
  logging: CLOUD_LOGGING_ONLY