
steps:
  - name: 'gcr.io/cloud-builders/gsutil'
    id: Fetch-DotEnv
    args: ['cp', '${_ENV}', '.env']

  - name: 'gcr.io/cloud-builders/docker'
    id: Build-Docker-Image
    # Asumsikan Dockerfile sekarang ada di root dari direktori yang di-submit (.)
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${_TAG_NAME}', '.']

  - name: 'gcr.io/cloud-builders/docker'
    id: Push-Docker-Image
    args: ['push', 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${_TAG_NAME}']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: Deploy-to-CloudRun
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${_TAG_NAME}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'

substitutions:
  _ENV: 'gs://bucketrawr/.env' # Ganti dengan path Cloud Storage Anda
  _SERVICE_NAME: 'artisanhubbackend' # Ganti dengan nama layanan Cloud Run Anda
  _REGION: 'us-central1' # Ganti dengan wilayah Cloud Run Anda (misal: us-central1, asia-southeast2)
  _TAG_NAME: 'latest' # Atau gunakan '$(BUILD_ID)' untuk tag unik per build
  # _TAG_NAME: '${_SERVICE_NAME}-$(date +%Y%m%d%H%M%S)-$(BUILD_ID)' # Contoh tag unik

options:
  logging: CLOUD_LOGGING_ONLY