
steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: Build Docker Image
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/backend-service', '.']

  - name: 'gcr.io/cloud-builders/docker'
    id: Push Docker Image
    args: ['push', 'gcr.io/$PROJECT_ID/backend-service']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: Deploy to Cloud Run
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'backend-service',
        '--image', 'gcr.io/$PROJECT_ID/backend-service',
        '--region', 'us-central1',
        '--platform', 'managed',
        '--allow-unauthenticated'
      ]

images:
  - 'gcr.io/$PROJECT_ID/backend-service'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  
  _SERVICE_NAME: 'artisanhubbackend' # Ganti dengan nama layanan Cloud Run Anda
  _REGION: 'us-central1' # Ganti dengan wilayah Cloud Run Anda (misal: us-central1, asia-southeast2)
  _TAG_NAME: 'latest' # Atau gunakan '$(BUILD_ID)' untuk tag unik per build
  # _TAG_NAME: '${_SERVICE_NAME}-$(date +%Y%m%d%H%M%S)-$(BUILD_ID)' # Contoh tag unik

options:
  logging: CLOUD_LOGGING_ONLY